name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS
      run: flutter build ipa --release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-app
        path: build/ios/ipa
